import { useState } from 'react';
import { Pressable, ScrollView, StyleSheet, View } from 'react-native';
import { Image } from 'expo-image';
import { Ionicons } from '@expo/vector-icons';
import { router, type Href } from 'expo-router';

import { AppText } from '@/components/ui/app-text';
import { AppScreen } from '@/components/ui/app-screen';
import { products } from '@/features/catalog/data/catalog';
import { theme } from '@/constants/theme';

export function OrdersScreen() {
  const [history, setHistory] = useState(false);
  const [quantities, setQuantities] = useState<Record<string, number>>({});
  const list = history ? [products[6], products[1]] : [products[3], products[5]];
  const changeQuantity = (id: string, by: number) => setQuantities((current) => ({ ...current, [id]: Math.max(1, (current[id] ?? 1) + by) }));
  return <AppScreen padded={false}><View style={styles.header}><AppText variant="label">My Order</AppText><Ionicons name="bag-handle-outline" size={19} /></View><View style={styles.tabs}><Pressable onPress={() => setHistory(false)} style={[styles.tab, !history && styles.active]}><AppText variant="label" color={!history ? theme.colors.ink : theme.colors.subtle}>My Order</AppText></Pressable><Pressable onPress={() => setHistory(true)} style={[styles.tab, history && styles.active]}><AppText variant="label" color={history ? theme.colors.ink : theme.colors.subtle}>History</AppText></Pressable></View><ScrollView contentContainerStyle={styles.content}>{list.map((product, index) => { const quantity = quantities[product.id] ?? 1; const unitPrice = product.price / (index + 1); return <View key={product.id} style={styles.card}><Image source={product.image} style={styles.image} contentFit="cover" /><View style={styles.copy}><View style={styles.title}><AppText variant="label" numberOfLines={2} style={{ flex: 1 }}>{product.name}</AppText><View style={[styles.badge, history && styles.complete]}><AppText variant="caption" color={history ? theme.colors.success : theme.colors.info}>{history ? 'Completed' : 'In Progress'}</AppText></View></View><AppText variant="caption" color={theme.colors.muted}>Color: {product.color}</AppText><View style={styles.quantityRow}><AppText variant="caption" color={theme.colors.muted}>Qty</AppText><View style={styles.stepper}><Pressable hitSlop={8} onPress={() => changeQuantity(product.id, -1)}><Ionicons name="remove" size={13} color={theme.colors.ink} /></Pressable><AppText variant="caption">{quantity}</AppText><Pressable hitSlop={8} onPress={() => changeQuantity(product.id, 1)}><Ionicons name="add" size={13} color={theme.colors.ink} /></Pressable></View></View><View style={styles.price}><AppText variant="caption">Price</AppText><AppText variant="subtitle">${(unitPrice * quantity).toFixed(2)}</AppText></View></View><View style={styles.actions}><Pressable style={styles.secondary} onPress={() => router.push(`/product/${product.id}` as Href)}><AppText variant="caption">Detail</AppText></Pressable><Pressable style={styles.primary} onPress={() => router.push(`/order-tracking?orderId=${product.id}` as Href)}><AppText variant="caption" color={theme.colors.white}>{history ? 'Received Order' : 'Tracking'}</AppText></Pressable></View></View>; })}</ScrollView></AppScreen>;
}
const styles = StyleSheet.create({ header: { height: 64, paddingHorizontal: 16, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 115 }, tabs: { height: 50, flexDirection: 'row', paddingHorizontal: 28 }, tab: { flex: 1, alignItems: 'center', justifyContent: 'center' }, active: { borderBottomWidth: 2, borderColor: theme.colors.violet }, content: { padding: 12, gap: 12 }, card: { minHeight: 148, padding: 10, borderRadius: theme.radius.md, backgroundColor: theme.colors.white, borderWidth: 1, borderColor: theme.colors.line, flexDirection: 'row', flexWrap: 'wrap', gap: 9 }, image: { width: 62, height: 70, borderRadius: theme.radius.sm }, copy: { flex: 1 }, title: { flexDirection: 'row', alignItems: 'flex-start' }, badge: { paddingHorizontal: 7, paddingVertical: 4, borderRadius: 10, backgroundColor: theme.colors.infoSoft }, complete: { backgroundColor: theme.colors.successSoft }, quantityRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginTop: 2 }, stepper: { width: 66, height: 22, paddingHorizontal: 7, borderRadius: 11, backgroundColor: theme.colors.surface, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, price: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 2 }, actions: { flexBasis: '100%', flexDirection: 'row', gap: 8 }, secondary: { flex: 1, height: 32, borderRadius: 16, borderWidth: 1, borderColor: theme.colors.line, alignItems: 'center', justifyContent: 'center' }, primary: { flex: 1, height: 32, borderRadius: 16, backgroundColor: theme.colors.violet, alignItems: 'center', justifyContent: 'center' } });
