import { Pressable, StyleSheet, View } from 'react-native';
import { Image } from 'expo-image';
import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { AppButton } from '@/components/ui/app-button';
import { AppText } from '@/components/ui/app-text';
import { theme } from '@/constants/theme';

const steps = [['Upbox Bag','Shop · 02:50 PM'],['On the way','Delivery · 03:20 PM'],['5482 Abode Falls Rd #155n Diego...','House · 03:45 PM']];
export function TrackingScreen() { return <View style={styles.root}><View style={styles.map}><Image source={require('../../../../assets/images/catalog/order-map.png')} style={StyleSheet.absoluteFill} contentFit="cover" /><Pressable style={styles.back} onPress={() => router.back()}><Ionicons name="chevron-back" size={20} /></Pressable><AppText variant="label" style={styles.title}>Order Tracking</AppText></View><View style={styles.sheet}><View style={styles.handle} /><View style={styles.driver}><View style={styles.avatar}><Ionicons name="person" size={22} /></View><View style={{ flex: 1 }}><AppText variant="label">Alexander Jr</AppText><AppText variant="caption" color={theme.colors.muted}>Courier</AppText></View><Ionicons name="chatbubble-outline" size={18} color={theme.colors.violet} /><Ionicons name="call-outline" size={18} color={theme.colors.violet} /></View><AppText variant="subtitle">Progress of your Order</AppText><View>{steps.map(([label, detail], index) => <View key={label} style={styles.step}><View style={[styles.stepIcon, index === 2 && styles.last]}><Ionicons name={index === 0 ? 'storefront-outline' : index === 1 ? 'bicycle-outline' : 'location-outline'} size={14} color={index === 2 ? theme.colors.body : theme.colors.white} /></View>{index < 2 ? <View style={styles.line} /> : null}<View><AppText variant="label">{label}</AppText><AppText variant="caption" color={theme.colors.muted}>{detail}</AppText></View></View>)}</View><AppButton variant="outline" label="Mark as Done" onPress={() => router.back()} /></View></View>; }
const styles = StyleSheet.create({ root: { flex: 1, backgroundColor: theme.colors.white }, map: { height: '49%' }, back: { position: 'absolute', top: 48, left: 14 }, title: { position: 'absolute', top: 50, alignSelf: 'center' }, sheet: { flex: 1, marginTop: -18, padding: 16, borderTopLeftRadius: 20, borderTopRightRadius: 20, backgroundColor: theme.colors.white, gap: 13 }, handle: { width: 52, height: 4, alignSelf: 'center', backgroundColor: theme.colors.lineStrong, borderRadius: 2 }, driver: { height: 58, flexDirection: 'row', alignItems: 'center', gap: 11 }, avatar: { width: 40, height: 40, borderRadius: 20, backgroundColor: '#E8E1DA', alignItems: 'center', justifyContent: 'center' }, step: { height: 58, flexDirection: 'row', gap: 12 }, stepIcon: { width: 28, height: 28, borderRadius: 14, backgroundColor: theme.colors.violet, alignItems: 'center', justifyContent: 'center' }, last: { backgroundColor: theme.colors.surfaceStrong }, line: { position: 'absolute', left: 13, top: 28, height: 30, borderLeftWidth: 2, borderColor: theme.colors.violet }, });
