import { useMemo, useState } from 'react';
import { Modal, Pressable, ScrollView, StyleSheet, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { router, useLocalSearchParams, type Href } from 'expo-router';

import { AppButton } from '@/components/ui/app-button';
import { AppScreen } from '@/components/ui/app-screen';
import { AppText } from '@/components/ui/app-text';
import { theme } from '@/constants/theme';
import { ProductCard } from '../components/product-card';
import { SearchBar } from '../components/search-bar';
import { products } from '../data/catalog';

const searches = ['Electronics', 'Pants', 'Three Second', 'Long shirt'];
const filters = ['All', 'Latest', 'Most Popular', 'Cheapest'];

export function SearchScreen() {
  const params = useLocalSearchParams<{ query?: string; category?: string }>();
  const [query, setQuery] = useState(params.query ?? (params.category ? 'BagBo...' : ''));
  const [active, setActive] = useState('All');
  const [filterOpen, setFilterOpen] = useState(false);
  const results = useMemo(() => products.filter((product) => !query || product.name.toLowerCase().includes(query.replace('...', '').toLowerCase()) || query.toLowerCase().includes('bag')), [query]);
  const showingResults = Boolean(query || params.category);
  return (
    <AppScreen padded={false}>
      <View style={styles.top}><Pressable onPress={() => router.back()}><Ionicons name="chevron-back" size={20} /></Pressable><View style={styles.search}><SearchBar value={query} onChangeText={setQuery} onFilter={() => setFilterOpen(true)} placeholder="Search" /></View></View>
      {showingResults ? <ScrollView contentContainerStyle={styles.results}><View style={styles.filters}>{filters.map((filter) => <Pressable key={filter} onPress={() => setActive(filter)} style={[styles.chip, active === filter && styles.activeChip]}><AppText variant="caption" color={active === filter ? theme.colors.white : theme.colors.muted}>{filter}</AppText></Pressable>)}</View><View style={styles.store}><View style={styles.storeIcon}>📦</View><View style={{ flex: 1 }}><AppText variant="label">Upbox Bag <Ionicons name="checkmark-circle" size={11} color={theme.colors.info} /></AppText><AppText variant="caption" color={theme.colors.muted}>104 Products · 1.3k Followers</AppText></View><Pressable onPress={() => router.push('/store/upbox-bag' as Href)}><Ionicons name="chevron-forward" size={16} color={theme.colors.subtle} /></Pressable></View><View style={styles.grid}>{results.map((product) => <ProductCard key={product.id} product={product} compact />)}</View></ScrollView> : <ScrollView contentContainerStyle={styles.empty}><View style={styles.sectionHeader}><AppText variant="subtitle">Last Search</AppText><Pressable><AppText variant="caption" color={theme.colors.violet}>Clear All</AppText></Pressable></View><View style={styles.history}>{searches.map((item) => <Pressable key={item} style={styles.historyChip} onPress={() => setQuery(item)}><AppText variant="caption" color={theme.colors.body}>{item}</AppText><Ionicons name="close" size={12} color={theme.colors.muted} /></Pressable>)}</View><AppText variant="subtitle" style={{ marginTop: 24 }}>Popular Search</AppText>{products.slice(0, 4).map((product, index) => <Pressable key={product.id} style={styles.popular} onPress={() => setQuery(product.name)}><ProductCard product={product} width={64} compact /><View style={styles.popularCopy}><AppText variant="label">{product.name}</AppText><AppText variant="caption" color={theme.colors.muted}>{(1 + index / 10).toFixed(1)}k Search today</AppText></View><View style={[styles.tag, { backgroundColor: index % 2 ? theme.colors.warningSoft : theme.colors.dangerSoft }]}><AppText variant="caption" color={index % 2 ? theme.colors.warning : theme.colors.danger}>{index % 2 ? 'New' : 'Hot'}</AppText></View></Pressable>)}</ScrollView>}
      <FilterSheet visible={filterOpen} onClose={() => setFilterOpen(false)} />
    </AppScreen>
  );
}

function FilterSheet({ visible, onClose }: { visible: boolean; onClose: () => void }) {
  return <Modal transparent visible={visible} animationType="slide" onRequestClose={onClose}><Pressable style={styles.overlay} onPress={onClose} /><View style={styles.sheet}><View style={styles.handle} /><AppText variant="subtitle" align="center">Filter By</AppText><AppText variant="label" style={styles.filterLabel}>Price <AppText variant="caption" color={theme.colors.muted}>       $0–$80</AppText></AppText><View style={styles.range}><View style={styles.rangeFill} /><View style={styles.knob} /><View style={[styles.knob, { left: '38%' }]} /></View><AppText variant="label" style={styles.filterLabel}>Color</AppText><View style={styles.colorRow}>{['#252438','#DCD3EF','#D4E5F3','#E8DAB8','#F1D4D4'].map((color) => <View key={color} style={[styles.color, { backgroundColor: color }]} />)}</View><AppText variant="label" style={styles.filterLabel}>Location</AppText><View style={styles.locationRow}>{['San Diego','New York','Amsterdam'].map((item, index) => <View key={item} style={[styles.location, index === 0 && styles.selectedLocation]}><AppText variant="caption" color={index === 0 ? theme.colors.white : theme.colors.violet}>{item}</AppText></View>)}</View><AppButton label="Apply Filter" onPress={onClose} /></View></Modal>;
}

const styles = StyleSheet.create({ top: { height: 65, paddingHorizontal: 12, flexDirection: 'row', alignItems: 'center', gap: 10 }, search: { flex: 1 }, empty: { paddingHorizontal: 16, paddingBottom: 30 }, sectionHeader: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 10 }, history: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, marginTop: 14 }, historyChip: { height: 34, paddingHorizontal: 13, borderRadius: 17, borderWidth: 1, borderColor: theme.colors.line, flexDirection: 'row', alignItems: 'center', gap: 8 }, popular: { height: 76, flexDirection: 'row', alignItems: 'center' }, popularCopy: { flex: 1, marginLeft: 10 }, tag: { paddingHorizontal: 10, paddingVertical: 6, borderRadius: 12 }, results: { paddingHorizontal: 11, paddingBottom: 30 }, filters: { flexDirection: 'row', gap: 7, marginBottom: 14 }, chip: { paddingHorizontal: 13, height: 27, borderRadius: 14, borderWidth: 1, borderColor: theme.colors.line, alignItems: 'center', justifyContent: 'center' }, activeChip: { backgroundColor: theme.colors.violet, borderColor: theme.colors.violet }, store: { height: 62, flexDirection: 'row', alignItems: 'center', gap: 10, borderBottomWidth: 1, borderColor: theme.colors.line, marginBottom: 14 }, storeIcon: { width: 38, height: 38, borderRadius: 19, backgroundColor: theme.colors.violetSoft, alignItems: 'center', justifyContent: 'center' }, grid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between' }, overlay: { position: 'absolute', top: 0, right: 0, bottom: 0, left: 0, backgroundColor: theme.colors.overlay }, sheet: { position: 'absolute', left: 0, right: 0, bottom: 0, padding: 16, paddingBottom: 28, backgroundColor: theme.colors.white, borderTopLeftRadius: 20, borderTopRightRadius: 20, gap: 14 }, handle: { width: 52, height: 4, alignSelf: 'center', borderRadius: 2, backgroundColor: theme.colors.lineStrong }, filterLabel: { marginTop: 4 }, range: { height: 18, justifyContent: 'center' }, rangeFill: { height: 2, backgroundColor: theme.colors.violet, width: '40%' }, knob: { position: 'absolute', left: 0, width: 11, height: 11, borderRadius: 6, borderWidth: 2, borderColor: theme.colors.violet, backgroundColor: theme.colors.white }, colorRow: { flexDirection: 'row', gap: 24 }, color: { width: 20, height: 20, borderRadius: 10 }, locationRow: { flexDirection: 'row', gap: 8, marginBottom: 8 }, location: { paddingHorizontal: 13, height: 34, borderRadius: 17, backgroundColor: theme.colors.violetSoft, alignItems: 'center', justifyContent: 'center' }, selectedLocation: { backgroundColor: theme.colors.violet } });
