import { Pressable, ScrollView, StyleSheet, View } from 'react-native';
import { Image } from 'expo-image';
import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';

import { AppScreen } from '@/components/ui/app-screen';
import { AppText } from '@/components/ui/app-text';
import { ProductCard } from '../components/product-card';
import { products } from '../data/catalog';
import { theme } from '@/constants/theme';

export function StoreScreen() {
  return <AppScreen padded={false}><ScrollView contentContainerStyle={styles.content}><View style={styles.header}><Pressable onPress={() => router.back()}><Ionicons name="chevron-back" size={20} /></Pressable><AppText variant="label">Store</AppText><Ionicons name="bag-handle-outline" size={19} /></View><View style={styles.store}><View style={styles.logo}>📦</View><View style={{ flex: 1 }}><AppText variant="subtitle">Upbox Bag <Ionicons name="checkmark-circle" size={12} color={theme.colors.info} /></AppText><AppText variant="caption" color={theme.colors.muted}>104 Products · 1.3k Followers</AppText></View><View style={styles.follow}><AppText variant="caption" color={theme.colors.white}>Follow</AppText></View></View><View style={styles.tabs}><View style={styles.active}><AppText variant="label">Main Page</AppText></View><AppText variant="label" color={theme.colors.subtle}>All Products</AppText><AppText variant="label" color={theme.colors.subtle}>Best Seller</AppText></View><View style={styles.banner}><View><AppText variant="subtitle" style={{ fontSize: 17 }}>35% discount, for the{`\n`}purchase of headphones</AppText><AppText variant="caption" color={theme.colors.muted}>By Upbox Bag</AppText></View><Image source={products[6].image} style={styles.bannerImage} contentFit="cover" /></View><View style={styles.dots}><View style={styles.dotActive} /><View style={styles.dot} /><View style={styles.dot} /></View><AppText variant="title" style={{ marginBottom: 14 }}>Popular Products</AppText><View style={styles.grid}>{products.slice(6, 9).concat(products.slice(2, 4)).map((product) => <ProductCard key={product.id} product={product} compact />)}</View></ScrollView></AppScreen>;
}
const styles = StyleSheet.create({ content: { paddingHorizontal: 12, paddingBottom: 30 }, header: { height: 55, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, store: { height: 64, flexDirection: 'row', alignItems: 'center', gap: 10 }, logo: { width: 40, height: 40, borderRadius: 20, backgroundColor: theme.colors.violetSoft, alignItems: 'center', justifyContent: 'center' }, follow: { paddingHorizontal: 16, paddingVertical: 9, backgroundColor: theme.colors.violet, borderRadius: 18 }, tabs: { height: 58, flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'space-around', borderBottomWidth: 1, borderColor: theme.colors.line }, active: { paddingHorizontal: 15, paddingBottom: 12, borderBottomWidth: 2, borderColor: theme.colors.violet }, banner: { height: 125, borderRadius: theme.radius.sm, backgroundColor: '#F4F1F4', overflow: 'hidden', padding: 16, justifyContent: 'center', marginTop: 15 }, bannerImage: { position: 'absolute', width: 145, height: 125, right: 0 }, dots: { height: 34, flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: 5 }, dotActive: { width: 6, height: 6, borderRadius: 3, backgroundColor: theme.colors.violet }, dot: { width: 6, height: 6, borderRadius: 3, backgroundColor: theme.colors.lineStrong }, grid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between' } });
