import { useState } from 'react';
import { KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, TextInput, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useLocalSearchParams } from 'expo-router';

import { AppHeader } from '@/components/ui/app-header';
import { AppText } from '@/components/ui/app-text';
import { products } from '@/features/catalog/data/catalog';
import { theme } from '@/constants/theme';
import { contacts } from '../data/communication';

export function ChatScreen() { const { id } = useLocalSearchParams<{ id: string }>(); const contact = contacts.find((item) => item.id === id) ?? contacts[0]; const [value, setValue] = useState(''); const [messages, setMessages] = useState(['Hi, I have purchased this product','Sent it soon ok']); return <KeyboardAvoidingView style={styles.root} behavior={Platform.OS === 'ios' ? 'padding' : undefined}><View style={styles.header}><AppHeader title="Message" right={<Ionicons name="notifications-outline" size={19} />} /><View style={styles.contact}><View style={styles.avatar}><Ionicons name="person" size={22} /></View><View style={{ flex: 1 }}><AppText variant="label">{contact.name}</AppText><AppText variant="caption" color={theme.colors.success}>Online</AppText></View><Ionicons name="videocam-outline" size={20} /><Ionicons name="call-outline" size={20} /></View></View><ScrollView contentContainerStyle={styles.chat}><View style={styles.out}><AppText variant="body" color={theme.colors.white}>{messages[0]}</AppText></View><View style={[styles.out, styles.product]}><AppText variant="label" color={theme.colors.white}>{products[3].name}</AppText><AppText variant="caption" color="#E3E2FF">Color: Brown</AppText></View><View style={styles.out}><AppText variant="body" color={theme.colors.white}>{messages[1]}</AppText></View><AppText variant="caption" color={theme.colors.muted} align="right">10:15 AM</AppText><View style={styles.in}><AppText variant="body">Hi Ahmir, Thanks for buying our product</AppText></View><View style={styles.in}><AppText variant="body">Your package will be packed soon</AppText></View></ScrollView><View style={styles.composer}><Ionicons name="camera-outline" size={18} color={theme.colors.subtle} /><TextInput value={value} onChangeText={setValue} placeholder="Type message..." placeholderTextColor={theme.colors.muted} style={styles.input} /><Ionicons name="mic-outline" size={18} color={theme.colors.subtle} /><Pressable style={styles.send} onPress={() => { if (value.trim()) { setMessages((current) => [...current, value]); setValue(''); } }}><Ionicons name="send" size={17} color={theme.colors.white} /></Pressable></View></KeyboardAvoidingView>; }
const styles = StyleSheet.create({ root: { flex: 1, backgroundColor: theme.colors.white }, header: { paddingHorizontal: 12 }, contact: { height: 58, flexDirection: 'row', alignItems: 'center', gap: 10, borderBottomWidth: 1, borderColor: theme.colors.line }, avatar: { width: 39, height: 39, borderRadius: 20, backgroundColor: '#E8D9D0', alignItems: 'center', justifyContent: 'center' }, chat: { flexGrow: 1, padding: 14, gap: 8 }, out: { maxWidth: '72%', alignSelf: 'flex-end', padding: 11, borderRadius: 12, borderBottomRightRadius: 3, backgroundColor: theme.colors.violet }, product: { minWidth: 190, minHeight: 64 }, in: { maxWidth: '72%', alignSelf: 'flex-start', padding: 11, borderRadius: 12, borderBottomLeftRadius: 3, backgroundColor: theme.colors.surfaceStrong }, composer: { minHeight: 60, margin: 12, paddingHorizontal: 11, borderWidth: 1, borderColor: theme.colors.lineStrong, borderRadius: 28, flexDirection: 'row', alignItems: 'center', gap: 8 }, input: { flex: 1, fontFamily: theme.type.regular, fontSize: 11 }, send: { width: 36, height: 36, borderRadius: 18, backgroundColor: theme.colors.violet, alignItems: 'center', justifyContent: 'center' } });
