import { Pressable, ScrollView, StyleSheet, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { router, type Href } from 'expo-router';

import { AppHeader } from '@/components/ui/app-header';
import { AppScreen } from '@/components/ui/app-screen';
import { AppText } from '@/components/ui/app-text';
import { SearchBar } from '@/features/catalog/components/search-bar';
import { theme } from '@/constants/theme';
import { contacts } from '../data/communication';

export function MessagesScreen() { return <AppScreen padded={false}><View style={styles.pad}><AppHeader title="Message" right={<View><Ionicons name="notifications-outline" size={19} /><View style={styles.red} /></View>} /><SearchBar onFilter={() => {}} /></View><ScrollView contentContainerStyle={styles.content}><AppText variant="subtitle">Activities</AppText><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.activities}>{contacts.map((contact, index) => <View key={contact.id} style={styles.activity}><View style={[styles.avatar, { backgroundColor: ['#EBD8D0','#D5E8F2','#EAD7D9','#DED4C7'][index] }]}><Ionicons name="person" size={23} /></View><AppText variant="caption">{contact.name.split(' ')[0]}</AppText></View>)}</ScrollView><AppText variant="subtitle">Messages</AppText>{contacts.map((contact, index) => <Pressable key={contact.id} style={styles.row} onPress={() => router.push(`/messages/${contact.id}` as Href)}><View style={[styles.avatar, { backgroundColor: ['#EBD8D0','#D5E8F2','#EAD7D9','#DED4C7'][index] }]}><Ionicons name="person" size={23} /></View><View style={styles.copy}><View style={styles.name}><AppText variant="label">{contact.name}</AppText><AppText variant="caption" color={theme.colors.muted}>{contact.time}</AppText></View><AppText variant="caption" color={theme.colors.body} numberOfLines={2}>{contact.message}</AppText></View>{contact.unread ? <View style={styles.unread}><AppText variant="caption" color={theme.colors.white}>{contact.unread}</AppText></View> : null}</Pressable>)}</ScrollView></AppScreen>; }
const styles = StyleSheet.create({ pad: { paddingHorizontal: 12 }, content: { padding: 12, gap: 12 }, red: { position: 'absolute', top: 0, right: 0, width: 6, height: 6, borderRadius: 3, backgroundColor: theme.colors.danger }, activities: { gap: 15 }, activity: { alignItems: 'center', gap: 4 }, avatar: { width: 45, height: 45, borderRadius: 23, borderWidth: 2, borderColor: theme.colors.violet, alignItems: 'center', justifyContent: 'center' }, row: { minHeight: 72, flexDirection: 'row', alignItems: 'center', gap: 10 }, copy: { flex: 1, gap: 4 }, name: { flexDirection: 'row', justifyContent: 'space-between' }, unread: { width: 18, height: 18, borderRadius: 9, backgroundColor: theme.colors.violet, alignItems: 'center', justifyContent: 'center' } });
